
/**
 * Describes the data associated with a single school using the system
 */
export interface Tenant {
	id: string; // Unique identifier for the tenant, generated by backend
	name: string;
	description?: string;
}

export interface Organization {
	id: string; // Unique identifier for the organization, generated by backend
	parentOrganizationID?: string; // Optional reference to a parent organization for hierarchical structures, if not available, this organization is a root organization
	tenantID: string;
	name: string;
	description?: string;
}

export interface AppUser {
	id: string; // Unique identifier for the user, generated by backend
	email: string;
	tenantID: string;
	organizationID: string;
}

export interface AppUserDetail 
	extends Pick<
		AppUser,
		"id" | "email" | "tenantID" | "organizationID"
	> {
	roleIDs: string[];
}

export interface AppUserUpsertPayload {
	email: string;
	organizationID: string;
	roleIDs: string[];
}

export interface Student {
	id: string; // Unique identifier for the student, generated by backend
	schoolStudentID: string; // Unique identifier for the student, pregenerated by school, entered manually into system by admin
	tenantID: string;
	firstName: string;
	lastName: string;
}

export interface StudentLunchCheck {
	studentID: string; // Refers to Student.id
	tenantID: string;
	contractSigned: boolean;
	note?: string;
}

export interface LunchCheckRecord {
	id: string; // Unique identifier for the lunch check record, generated by backend
	tenantID: string;
	studentID: string; // Refers to Student.id
	lunchDate: string; // ISO date string (e.g., "2024-01-01")
	checkInTime?: Date;
	checkOutTime?: Date;
	createdDate: Date; // Timestamp for when the record was created
}

export interface StudentLunchCheckCompositeRecord {
	student: Student;
	studentLunchCheck?: StudentLunchCheck;
	lunchCheckRecords: LunchCheckRecord[];
}

export interface QueryStudentLunchCheckResponse {
	records: StudentLunchCheckCompositeRecord[];
	totalRecords: number;
	pageNumber: number; // Real page number being returned based on the number of records and page size, this may differ from the requested page number if the requested page number is out of range
	pageSize: number; // Real page size being returned based on the number of records and page size, this may differ from the requested page size if the requested page size is out of range
}

export interface SaveStudentLunchCheckRequest {
	studentID: string; // Refers to Student.id
	lunchDate: string; // ISO date string (e.g., "2024-01-01")
	checkingIn: boolean; // true if checking in, false if checking out
}

export interface SaveStudentLunchCheckResponse {
	lunchCheckRecord: LunchCheckRecord; // Record that just got saved
}

export interface QueryStudentLunchCheckRequest {
	schoolStudentID?: string; // Refers to Student.schoolStudentID
	firstName?: string;
	lastName?: string;
	lunchDate: string; // ISO date string (e.g., "2024-01-01")
	pageNumber?: number;
	pageSize?: number;
}

export interface GetStudentLunchCheckInAndOutHistoryRequest {
	studentID: string; // Refers to Student.id
	startDate?: string; // ISO date string (e.g., "2024-01-01")
	endDate?: string; // ISO date string (e.g., "2024-01-01")
	pageNumber?: number;
	pageSize?: number;
}

export interface GetStudentLunchCheckInAndOutHistoryResponse {
	records: LunchCheckRecord[];
	totalRecords: number;
	pageNumber: number; // Real page number being returned based on the number of records and page size, this may differ from the requested page number if the requested page number is out of range
	pageSize: number; // Real page size being returned based on the number of records and page size, this may differ from the requested page size if the requested page size is out of range
}

export interface AppUserSession {
	sessionID: string; // Unique identifier for the session, generated by backend
	tenantID: string;
	userID: string;
	tenantName: string;
	organizationID: string;
	organizationName: string;
}

export interface AppRole {
	id: string; // UUID
	tenantID: string;
	name: string;
	description: string;
	appPermissions: string[];
}

export interface UserRole {
	tenantID: string;
	appUserID: string;
	appRoleID: string;
}

export interface GeneralAPIResponse {
	success: boolean;
	message?: string;
}

export interface SaveStudentLunchCheckConfigRequest {
	studentID: string;
	contractSigned: boolean;
	note?: string;
}

export interface SaveStudentLunchCheckConfigResponse {
	studentLunchCheck: StudentLunchCheck;
}