
/**
 * Describes the data associated with a single school using the system
 */
export interface Tenant {
	id: string; // Unique identifier for the tenant, generated by backend
	name: string;
	description?: string;
}

export interface Organization {
	id: string; // Unique identifier for the organization, generated by backend
	parentOrganizationID?: string; // Optional reference to a parent organization for hierarchical structures, if not available, this organization is a root organization
	tenantID: string;
	name: string;
	description?: string;
}

export interface AppUser {
	id: string; // Unique identifier for the user, generated by backend
	email: string;
	tenantID: string;
	organizationID: string;
}