
/**
 * Describes the data associated with a single school using the system
 */
export interface Tenant {
	id: string; // Unique identifier for the tenant, generated by backend
	name: string;
	description?: string;
}